### ISSUE TITLE
How are renames and deletes handled by uJet?

### ISSUE THREAD

**Issue by Myster** [logikfabrik/uJet#1]

**Comment by logikfabrik** [comment]
I'm guessing you're asking about properties? Renames and deletes are not currently tracked by uJet; changing a property name will trigger uJet to create a new property in the back office and deleting a property will have no effect on the back office.
Tracking support is planned for the next major release.

**Comment by CodeCheetah** [comment]
Hi Anton,

Has this been implemented in the latest release yet? I have been using uSiteBuilder for awhile maybe worth including [Obsolete] annotation to remove redundant properties in Umbraco?

Andrew

**Comment by logikfabrik** [comment]
Hi Andrew,

Type and property tracking has been supported since version 3 by setting the Id attribute; see [Type Tracking](http://ujet.readthedocs.org/en/dev/working_with_types.html#type-tracking), and [Property Tracking](http://ujet.readthedocs.org/en/dev/working_with_properties.html#property-tracking) in the documentation. Version 4 is on its way; [https://www.nuget.org/packages/uJet/4.0.0-beta](https://www.nuget.org/packages/uJet/4.0.0-beta).

Renaming a type or property in code will cause uJet to make changes to the DB (on application start). Deleting a type or property will not; this is by design. uJet cannot seperate a type or property added manually through the backoffice from one that's been deleted in code. That's why deleted types and properties must also be deleted by hand in the back office.

You can tell uJet to ignore a property by decorating the property using [ScaffoldColumnAttribute](http://ujet.readthedocs.org/en/dev/working_with_properties.html#scaffoldcolumnattribute).

I hope that answers your question.
