### ISSUE TITLE
Nested Content Compatibility

### ISSUE THREAD

**Issue by iahdevelop** [logikfabrik/uJet#2]
Hello Anton 

I'm just looking to use code approach in my Umbraco projects and i am relying a lot on NestedContent (https://github.com/leekelleher/umbraco-nested-content)
So, does uJet support  NestedContent or Architype? If so could you give me an example.

Many thanks,

**Comment by logikfabrik** [comment]
Hi,

When trying Nested Content together with uJet I found that the latest Umbraco version (7.2.8) and uJet are incompatible. I suspect the incompatibility is isolated to the `JetViewEngine` class, but an incompatibility in the view engine will break support for typed views. I'll be looking into this. Considering the current incompatibility my answer regarding Nested Content is no. But as soon as this has been fixed the same answer for Archetype will be true for Nested Content.

So, Archetype. To support Archetype there are some things you'll need to do. Set up Archetype as usual, create your Archetype data type. Create your document type (don't forget to decorate it using the `DocumentType` attribute), create a model class representing the Archetype data type and use it as a public property in your document type. The final step is to create a data type mapping for your Archetype model class, which will make it possible for uJet to read the property data from the Umbraco database. The data type mapping is created by implementing the `IDataTypeDefinitionMapping` interface and adding it to the list of available mappings. You can find an example of how to do this in the uJetMaps repo here on GitHub, and more information in the uJet manual.

Good luck, and let me know if you have any more questions.

**Comment by iahdevelop** [comment]
Thank you Anton

**Comment by logikfabrik** [comment]
No problem. By the way, uJet now supports Umbraco 7.2.8.

**Comment by CodeCheetah** [comment]
Hi Anton,

I'm keen to find out if this has been implemented in the latest release yet? I have been using uSiteBuilder for awhile but since its no longer maintained I'm looking for alternatives.

I have used uSiteBuilder with Archetype and it worked without problems by setting pre-values as below.

`using Vega.USiteBuilder;

namespace Extensions.DataTypes
{
	/// <summary>
	/// Defines the data type.
	/// </summary>
	[DataType(Name = "List",
		UniqueId = "578ad7d9-9792-452f-91f2-18cf98d37969",
		PropertyEditorAlias = "Imulus.Archetype",
		DataTypeDatabaseType = DataTypeDatabaseType.Ntext
	)]
	public class BrandNameList : DataTypeBase
	{
		/// <summary>
		/// Gets the pre-values for the data type.
		/// </summary>
		public override DataTypePrevalue[] Prevalues
		{
			get
			{
				return new[]
				{
					new DataTypePrevalue("archetypeConfig", @"
{
	'showAdvancedOptions': true,
	'startWithAddButton': false,
	'hideFieldsetToolbar': false,
	'enableMultipleFieldsets': false,
	'hideFieldsetControls': false,
	'hidePropertyLabel': false,
	'maxFieldsets': null,
	'enableCollapsing': true,
	'enableCloning': false,
	'enableDisabling': true,
	'enableDeepDatatypeRequests': false,
	'fieldsets': [
		{
			'alias': 'brandNames',
			'remove': false,
			'collapse': false,
			'labelTemplate': '{{name}}',
			'icon': '',
			'label': 'Brand Names',
			'properties': [
								{
					'alias': 'name',
					'remove': false,
					'collapse': true,
					'label': 'Name',
					'helpText': '',
					'dataTypeGuid': '0cc0eba1-9960-42c9-bf9b-60e150b429ae',
					'value': '',
					'aliasIsDirty': true,
					'required': true
				}
			]
		}
	]
}"),
					new DataTypePrevalue("hideLabel", "0")
				};
			}
		}
	}
}`

Can I do the same with uJet? I have looked at the uJetMaps and Felice projects and having no luck.

Many thanks,


Andrew

**Comment by logikfabrik** [comment]
Hi,

No, sorry. Prevalues are not supported by uJet.

The use of mappings are for converting data type values from Umbraco to your models (perhaps into complex types) and back. This is a feature for when working with the MVC parts of uJet. I figure that's why you haven't had any luck looking at the other projects.

I'm going to create and issue to add this support. If you have any thoughts as to how it can/should be implemented I'd appreciate it. If you'd like to add it to uJet yourself even better!

**Comment by logikfabrik** [comment]
Pre-values are now supported. See [https://www.nuget.org/packages/uJet/4.0.0-beta2](https://www.nuget.org/packages/uJet/4.0.0-beta2).
