### ISSUE TITLE
Add logging

### ISSUE THREAD

**Issue by logikfabrik** [logikfabrik/uJet#8]
Today uJet logs nothing. This complicates troubleshooting and sanity checks. We need to add logging to all parts of uJet.

**Comment by ActionCommunity** [comment]
Anton,
By working in a agile way, what you are actually doing, this can be done step by step, when it's needed. The only important thing you need to care about is, that your implementations are in that way you later want to use. 
When speaking about logging I already define a logging helper with the simplest methods needed. These are acting then add wrappers. For example by implementing the ILogger interface of log4net and these static service than can simply log into Umbraco log or wherever. This is the node solution.
I'm writing with my mobile so I have no code access but I think Umbraco implements log4net at all.
And now, when searching for the bug that document types are imported even if nothing is configured in web.config you simply add the need logging info add debug, so when logger is in debug mode you will see your log lines which makes it very fast to find the problem with startup and config. No application debugging is needed further more at this point, and you have a nice helper layer when getting problems in production. 
Agile = Step by Step I realize very big projects in that way since years, with success. 
1. KISS principle
2. Avoid overengineering and implement only what you need
In 20 mins I can switch on pc and then I can send you an maybe interesting code example for logging mechanism.
Michael
Am 31.12.2015 09:53 schrieb Anton Frennevi <notifications@github.com>:Today uJet logs nothing This complicates troubleshooting and sanity checks We need to add logging to all parts of uJet

**Comment by ActionCommunity** [comment]
Anton, 

 

I attached 2 files of my current test system. LogIndent can be used as follows:

 

using(new Logindent(this, “Running service”)){

              // Dp your stuff

}

 

On the other side, the Logger class does use Trace log or console when compiled as JS. I have this classes in shared project which is compiled into C# on one site and on the other site into JS with Bridge. However, using something like Logger with own implementation which is using the umbraco logging service should do the job well.

 

You should aboid to use the umbraoc logging service directly, if doing so, you later have no chance to easily add logging targets ot changing the logging system,

 

Michael

**Comment by logikfabrik** [comment]
I see you have ideas about the logging. So I'm assigning this issue to you instead. :)

**Comment by ActionCommunity** [comment]
Anton,

to avoid over enginerring, please specify your requirements. I suggest to:

- simply implement a static logger which directly logs into the umbraco backend logging

I think, for now, we dont need connections to other logging frameworks like  log4net. What do you think?

**Comment by logikfabrik** [comment]
I'm with you on this. We don't need to make it any more complicated than it has to be.

I know Umbraco has its own logging wrapper (for log4net). How about using that wrapper? I think it would be helpful if uJet uses the same logging config as Umbraco as a whole. That way, if a user knows how to configure Umbraco logging, then he knows how to configure uJet logging.

What do you think?

**Comment by ActionCommunity** [comment]
Anton,
Yeah you are right adding additional config option is overhead too. In our case maybe providing an additional abstraction layer on top of Umbraco logging can be seen as overhead at all.  We will not use it heavily, so maybe using the standard logging on our case can be enough. I'm not really sure! Having a smart abstraction layer is from design point of view normally a must have :)
Am 21.01.2016 07:15 schrieb Anton Frennevi <notifications@github.com>:I'm with you on this. We don't need to make it any more complicated than it has to be.

I know Umbraco has its own logging wrapper (for log4net). How about using that wrapper? I think it would be helpful if uJet uses the same logging config as Umbraco as a whole. That way, if a user knows how to configure Umbraco logging, then he knows how to configure uJet logging.

What do you think?

**Comment by logikfabrik** [comment]
I think a small lightweight wrapper of the Umbraco logging wrapper would be nice, I don't think it's overhead - we can just keep it light.

**Comment by ActionCommunity** [comment]
Okay, im with you with that! So in short:

*Feature: Logging wrapper for uJet*
> As a developer of uJet
> In order to use the integrated logging of Umbraco
> I want to have a easy to use wrapper for logging into the Umbraco system
> And behind the scenes this wrapper is connected directly to the methods of the LogHelper

*Scenario: Static logging mechanism*
> Given I have a using for "Logikfabrik.Umbraco.Jet.Extensions"
> When I use the static class LoggingExtensions
> Then I can use the static method Debug<T>(this T sender, string msg) to log a debug message
> And I can use the static method Info<T>(this T sender, string msg) to log a info message
> And I can use the static method Warn<T>(this T sender, string msg, Exception exc) to log a warning
> And I can use the static method Fatal<T>(this T sender, string msg, Exception exc = null) to log a fatal error

*Scenario: Static object extensions*
> Given I have a using for "Logikfabrik.Umbraco.Jet.Extensions"
> When I now review the methods of every object
> Then I can use the static method Debug(string msg) to log a debug message
> And I can use the static method Info(string msg) to log a info message
> And I can use the static method Warn(string msg, Exception exc) to log a warning
> And I can use the static method Fatal(string msg, Exception exc = null) to log a fatal error

Is that correct? Any additional wishes?

**Comment by logikfabrik** [comment]
Sounds great! That should cover it.

**Comment by ActionCommunity** [comment]
Anton, I just added a simple wrapper library as described above. This is too small for adding unit tests. I just tried it life with my sources and it seems to work. Can you check this please?

**Comment by logikfabrik** [comment]
Great! I'll look at it later tonight.

**Comment by logikfabrik** [comment]
Looks good, that's great! So all we need to do now is start using it.

**Comment by ActionCommunity** [comment]
Yeah :)
Am 02.02.2016 06:10 schrieb Anton Frennevi <notifications@github.com>:Looks good, that's great! So all we need to do now is start using it.
